name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Format check
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -D warnings

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rcp

  deploy:
    needs: [ docker-build ]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag Docker Image
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/rcp:${{ github.sha }}
          docker tag rcp $IMAGE_TAG
          echo $IMAGE_TAG >> image_tag.txt
      - name: Push Docker Image
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          docker push $IMAGE_TAG